sudo: required
services:
  - docker

before_install:
  - docker build -t nguyenduyhung1979/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true nguyenduyhung1979/react-test npm test

after_success:
  - docker build -t nguyenduyhung1979/multi-client ./client
  - docker build -t nguyenduyhung1979/multi-nginx ./nginx
  - docker build -t nguyenduyhung1979/multi-server ./server
  - docker build -t nguyenduyhung1979/multi-worker ./worker
  # Login to docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those image and push them to docker hub
  - docket push nguyenduyhung1979/multi-client
  - docket push nguyenduyhung1979/multi-nginx
  - docket push nguyenduyhung1979/multi-server
  - docket push nguyenduyhung1979/multi-worker